#!/bin/bash

# Set variables

RELEASE=$1

##### CHECK PART #####

# Check if Version.ini exists

if [ ! -e Version.ini ] ; then
  echo "Version.ini does not exist - initialize it somehow!"
  exit 1
fi

# Check that we have the release argument

if [ -z $1 ] ; then
  echo "Usage: $0 <releasename>"
  echo "Where <releasename> is one of those found in Version.ini"
  exit 1
fi

if [ -z $EDITOR ] ; then
  EDITOR=`which vim`
fi

# Check that the named release is good

VERSIONISGOOD=`CheckReleaseName.exe ${RELEASE}`
if [ $VERSIONISGOOD == 'Unknown' ] ; then
  echo "Release name '$RELEASE' is not recognized"
  exit 1
fi

# Check if working directory is clean

WKDIRCLEAN=`git status | grep "working directory clean" | wc -l`
if [ $WKDIRCLEAN -eq 0 ] ; then
  echo Working directory is not clean! Please take care of that and try again!
  git status
  exit 1
fi

##### END CHECK PART #####

##### DO STUFF PART #####

git checkout $RELEASE

VersionBumper.exe $RELEASE

NEWVERSION=`GetReleaseVersion.exe ${RELEASE}`
echo "Releasing new $RELEASE version ${NEWVERSION}!"
echo "${RELEASE} release ${NEWVERSION}" >CurrentRelease.txt
echo " " >>CurrentRelease.txt
git shortlog ${RELEASE}..development >>CurrentRelease.txt
echo "=======================================================================" >>CurrentRelease.txt
echo " " >>CurrentRelease.txt

git merge development

$EDITOR CurrentRelease.txt

if [ -e TempRelNotes.txt ] ; then
  rm TempRelNotes.txt
fi

cp CurrentRelease.txt TempRelNotes.txt
cat ReleaseNotes.txt >>TempRelNotes.txt
rm ReleaseNotes.txt
mv TempRelNotes.txt ReleaseNotes.txt
rm CurrentRelease.txt

# Update all AssemblyInfo.cs files
AssemblyInfoUpdater.exe ${RELEASE}

git add --update
git commit -m"Releasing ${RELEASE} ${NEWVERSION}"
git tag -a ${RELEASE}-${NEWVERSION} -m"${RELEASE} release ${NEWVERSION}"
git push origin ${RELEASE} --tags
git checkout development
git merge ${RELEASE}
git push origin development

##### END DO STUFF PART #####
